CREATE TABLE CUSTOMERS(
CUSTOMER_ID 	NUMBER(5) NOT NULL,
FIRST_NAME  	VARCHAR2(100) NOT NULL,
LAST_NAME 		VARCHAR2(100),
EMAIL_PERSONAL  VARCHAR2(255) NOT NULL,
EMAIL_OFFICE  	VARCHAR2(255),
MEMBERSHIP_NO 	NUMBER(5),
LOYALTY_POINT 	NUMBER(5),
CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE INDEX IDX_CUSTOMER_ID ON CUSTOMERS (CUSTOMER_ID);

COMMENT ON TABLE CUSTOMERS IS 'Store customer info';
COMMENT ON COLUMN CUSTOMERS.CUSTOMER_ID IS 'Primary key reference';
COMMENT ON COLUMN CUSTOMERS.FIRST_NAME IS 'Customer first name';
COMMENT ON COLUMN CUSTOMERS.LAST_NAME IS 'Customer last name';
COMMENT ON COLUMN CUSTOMERS.EMAIL_PERSONAL IS 'Main destination for order delivery';
COMMENT ON COLUMN CUSTOMERS.EMAIL_OFFICE IS 'Alternate destination for order delivery';
COMMENT ON COLUMN CUSTOMERS.MEMBERSHIP_NO IS 'Membership number for loyalty program';
COMMENT ON COLUMN CUSTOMERS.LOYALTY_POINT IS 'Store accumulated loyalty point';



CREATE TABLE PRODUCTS(
ITEM_NO        NUMBER(5) NOT NULL,
BOOK_TITLE     VARCHAR2(100) NOT NULL,
BOOK_AUTHOR    VARCHAR2(100) NOT NULL,
BOOK_PRICE     NUMBER(8,2) NOT NULL,
BOOK_QUANTITY  NUMBER(5) DEFAULT 0,
DISCOUNT_RATE  NUMBER(4,2) NOT NULL,
CONSTRAINT PK_PRODUCTS PRIMARY KEY (ITEM_NO)
);

CREATE INDEX IDX_ITEM_NO ON CUSTOMERS (ITEM_NO);

COMMENT ON TABLE PRODUCTS IS 'Store product info';
COMMENT ON COLUMN PRODUCTS.ITEM_NO IS 'Primary key reference';
COMMENT ON COLUMN PRODUCTS.BOOK_TITLE IS 'Book title';
COMMENT ON COLUMN PRODUCTS.BOOK_AUTHOR IS 'Author name';
COMMENT ON COLUMN PRODUCTS.BOOK_PRICE IS 'Price';
COMMENT ON COLUMN PRODUCTS.BOOK_QUANTITY IS 'Amount in stock';
COMMENT ON COLUMN PRODUCTS.DISCOUNT_RATE IS 'Discount amount';



CREATE TABLE ORDERS(
ORDER_NO    NUMBER(5) NOT NULL,
ORDER_DATE  DATE DEFAULT SYSDATE,
SHIP_DATE   DATE, 
CUST_NO		NUMBER(5) NOT NULL,
SHIP_TO     VARCHAR2(255) NOT NULL,
CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_NO),
CONSTRAINT FK_ORDERS__CUST_NO FOREIGN KEY (CUST_NO) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX IDX_ORDER_NO ON ORDERS (ORDER_NO);

COMMENT ON TABLE ORDERS IS 'Store order info';
COMMENT ON COLUMN ORDERS.ORDER_NO IS 'Order number';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS 'Order date';
COMMENT ON COLUMN ORDERS.SHIP_DATE IS 'Delivery date';
COMMENT ON COLUMN ORDERS.CUST_NO IS 'Customer ID';
COMMENT ON COLUMN ORDERS.SHIP_TO IS 'Email address item delivered to';



CREATE TABLE ORDER_DETAILS(
ORDER_NO    NUMBER(5) NOT NULL,
ITEM_NO     NUMBER(5) NOT NULL,
QTY			NUMBER(3) NOT NULL,
PRICE 		NUMBER(8,2) NOT NULL,
CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (ORDER_NO,ITEM_NO),
CONSTRAINT FK_ORDER_DETAILS__ORDER_NO FOREIGN KEY (CUST_NO) REFERENCES ORDERS (ORDER_NO),
CONSTRAINT FK_ORDER_DETAILS__ITEM_NO FOREIGN KEY (CUST_NO) REFERENCES PRODUCTS (ITEM_NO),
CONSTRAINT ORDER_DETAILS_QTY_CHK CHECK (QTY >=1)
);

COMMENT ON TABLE ORDER_DETAILS IS 'Store detail info per order';
COMMENT ON COLUMN ORDER_DETAILS.ORDER_NO IS 'Order number';
COMMENT ON COLUMN ORDER_DETAILS.ITEM_NO IS 'Product item no';
COMMENT ON COLUMN ORDER_DETAILS.QTY IS 'Amount per item';
COMMENT ON COLUMN ORDER_DETAILS.PRICE IS 'Price per item';