--customers
INSERT INTO CUSTOMERS VALUES(1,'Terry','Mong','terrytest123@test.com','',1,1);
INSERT INTO CUSTOMERS VALUES(2,'Albert','','bertdummytest@hotmail.com','',2,2);
INSERT INTO CUSTOMERS VALUES(3,'Kisha','Reez','123kishareez@mockup.com','',3,0);
INSERT INTO CUSTOMERS VALUES(4,'Amy','Lee','amymimi@whoami.com','',4,1);
INSERT INTO CUSTOMERS VALUES(5,'Scott','','scottheylang@gaah.com','',5,0);

--products
INSERT INTO PRODUCTS VALUES(1,'Starry Night','Leon',3.5,30,0.1);
INSERT INTO PRODUCTS VALUES(2,'Little Prince','The Famous Author',7.8,100,0.5);
INSERT INTO PRODUCTS VALUES(3,'Tip For Solo Traveller','Miss Sheldon',5.0,20,0.2);
INSERT INTO PRODUCTS VALUES(4,'Trading For Dummies','Stock Broker',10.0,50,0.0);
INSERT INTO PRODUCTS VALUES(5,'Hello Music','Lizzy',4.3,10,0.3);

--orders
INSERT INTO ORDERS VALUES(1,TO_DATE('01/02/2024','DD/MM/YYYY'),TO_DATE('02/02/2024','DD/MM/YYYY'),1,'terrytest123@test.com');
INSERT INTO ORDERS VALUES(2,TO_DATE('10/01/2024','DD/MM/YYYY'),'',3,'123kishareez@mockup.com');
INSERT INTO ORDERS VALUES(3,TO_DATE('15/03/2024','DD/MM/YYYY'),TO_DATE('17/03/2024','DD/MM/YYYY'),2,'bertdummytest@hotmail.com');
INSERT INTO ORDERS VALUES(4,TO_DATE('03/06/2024','DD/MM/YYYY'),'',4,'amymimi@whoami.com');

--order_details
INSERT INTO ORDER_DETAILS VALUES(1,2,2,7.8);
INSERT INTO ORDER_DETAILS VALUES(1,1,1,3.5);
INSERT INTO ORDER_DETAILS VALUES(1,3,1,5.0);
INSERT INTO ORDER_DETAILS VALUES(2,1,1,3.5);
INSERT INTO ORDER_DETAILS VALUES(2,2,1,7.8);
INSERT INTO ORDER_DETAILS VALUES(2,3,1,5.0);
INSERT INTO ORDER_DETAILS VALUES(2,4,1,10.0);
INSERT INTO ORDER_DETAILS VALUES(2,5,1,4.3);
INSERT INTO ORDER_DETAILS VALUES(3,5,1,4.3);
INSERT INTO ORDER_DETAILS VALUES(3,4,1,10.0);
INSERT INTO ORDER_DETAILS VALUES(4,1,1,3.5);