CREATE OR REPLACE TRIGGER TRI_ORDERS_CHECKTIME
BEFORE INSERT OR DELETE OR UPDATE
ON ORDERS
FOR EACH ROW

BEGIN
	IF TO_CHAR(SYSDATE,'HH24') < 9 OR TO_CHAR(SYSDATE,'HH24') > 23 THEN
		RAISE_APPLICATION_ERROR(-20011,'CANNOT MAKE NEW ORDER BEFORE 9 AM AND AFTER 11 PM');
	END IF;
END;