CREATE OR REPLACE TRIGGER TRI_ORDER_DETAILS_CHECKITEMCOUNT
BEFORE INSERT OR UPDATE
ON ORDER_DETAILS
FOR EACH ROW

DECLARE 
	V_CNT    NUMBER(5);
	
BEGIN

	SELECT COUNT(*) INTO V_CNT 
	FROM ORDER_DETAILS WHERE ORDER_NO = :NEW.ORDER_NO;
	
	IF V_CNT >5 THEN
		RAISE_APPLICATION_ERROR(-20010,'CANNOT EXCEED 5 ITEMS PER ORDER');
	END IF;

END;